server:
    port: 9000

security:
    basic:
        enable: false
management:
    security:
        enabled: false

spring:
    application:
        name: imit.school.registry
    liquibase:
        change-log: classpath:db/changelog/changelog-master.xml
        enabled: true
    jpa:
        show-sql: false
        open-in-view: false
        database: postgresql
        generate-ddl: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
                jdbc:
                    lob:
                        non_contextual_creation: true
    datasource:
        url: jdbc:postgresql://localhost:5432/imit_school_registry
        username: postgres
        password: postgres
        driverClassName: org.postgresql.Driver