name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          ARGS: '-avzr --delete'
          SOURCE: '.'
          TARGET: '~/web/backend'

      - name: ls -a via ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: "cd web && docker compose down && docker compose up -d"
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}